---
chapter: 3
knit: "bookdown::render_book"
---

# PREDICTING SLEEP STATE IN HUMAN PD PATIENTS {#ch3:jsr}

* The contents of this chapter are available from the directly from the [publisher](https://doi.org/10.1111/jsr.12806)^[This chapter was previously published in [@Christensen:2019ik] Journal of Sleep Research and is included with permission from the copyright holder]

* [[pdf](http://www.jzlab.org/Christensen_JSleepResearch2018_LFP_ANN_DBS.pdf)] [[Source Code](https://github.com/jzlab/sleep_net)]


## Abstract

Parkinson's disease (PD) is highly comorbid with sleep dysfunction. In contrast to motor symptoms, few therapeutic interventions exist to address sleep symptoms in PD. Subthalamic nucleus (STN) deep brain stimulation (DBS) treats advanced PD motor symptoms and may improve sleep architecture. As a proof of concept toward demonstrating that STN‐DBS could be used to identify sleep stages commensurate with clinician‐scored polysomnography (PSG), we developed a novel artificial neural network (ANN) that could trigger targeted stimulation in response to inferred sleep state from STN local field potentials (LFPs) recorded from implanted DBS electrodes. STN LFP recordings were collected from nine PD patients via a percutaneous cable attached to the DBS lead, during a full night's sleep (6–8 hr) with concurrent polysomnography (PSG). We trained a feedforward neural network to prospectively identify sleep stage with PSG‐level accuracy from 30‐s epochs of LFP recordings. Our model's sleep‐stage predictions match clinician‐identified sleep stage with a mean accuracy of 91% on held‐out epochs. Furthermore, leave‐one‐group‐out analysis also demonstrates 91% mean classification accuracy for novel subjects. These results, which classify sleep stage across a typical heterogenous sample of PD patients, may indicate spectral biomarkers for automatically scoring sleep stage in PD patients with implanted DBS devices. Further development of this model may also focus on adapting stimulation during specific sleep stages to treat targeted sleep deficits.
